# å…¨å±€èƒŒæ™¯å›¾
background:
  # æ˜¯å¦å¯ç”¨
  enable: true
  # èƒŒæ™¯å›¾ç‰‡
  url: /img/bg.jpg
  # èƒŒæ™¯å›¾ç‰‡çš„ä½ç½®
  position: center
  # èƒŒæ™¯å›¾ç‰‡æ˜¯å¦å›ºå®šä¸éšé¡µé¢æ»šåŠ¨
  fixed: true
  # æ˜¯å¦é‡å¤å¹³é“º
  repeat: no-repeat
  # èƒŒæ™¯å›¾ç‰‡å¤§å° 
  size: cover

# é¡µé¢é¡¶éƒ¨å¤§å›¾
index:
  banner_img: /img/wallpaper1.png
  banner_img_height: 100
  slogan:
    enable: true
    text: "ğŸ•ğŸ±"

# å¯¼èˆªèœå•
navbar:
  blog_title: # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config.title æ˜¾ç¤º
  ground_glass:
    enable: true
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
    - { key: "tetris", link: "/tetris/", icon: "iconfont icon-gamepad" }

# ä¾§è¾¹æ 
sidebar:
  # ä¾§è¾¹æ ä½ç½®ï¼Œå¯é€‰å€¼ï¼šleft | right
  position: right
  # ä¾§è¾¹æ è·ç¦»é¡¶éƒ¨è·ç¦» (æ”¯æŒ px å’Œ % ç­‰å•ä½)
  offsetTop: 20px
  # ä¾§è¾¹æ åŠ¨ç”»
  animation: false
  # æ˜¯å¦æ˜¾ç¤ºé¢å¤–çš„å›¾æ ‡
  icons: true
  # æ˜¯å¦æ˜¾ç¤ºé¢å¤–çš„æ–‡æœ¬
  text: true
  # ä¾§è¾¹æ è‡ªå®šä¹‰å°éƒ¨ä»¶
  widgets:
    - class: games
      display: true

# è‡ªå®šä¹‰ CSS
custom_css: /css/custom.css
